# Many data points from https://ssd.jpl.nasa.gov/horizons/app.html
# See `scripts/update-presets.py` for timestamps

# Schema:
# name: Title Case
# docname?: mid-sentence case with Proper Noun
# description?: mid-sentence case with Proper Noun
# mass: kg
# radius: metres
# apoapsis: metres | eccentricity: dimensionless # some sources use the latter, some the former
# inclination (degrees to parent's equator)
# arg_pe (degrees)
# long_asc_node (degrees)
# mean_anomaly (degrees)
# color (sRGB, [u8; 3|4] | u32)

################ STARS ################

[the_sun]
name = "The Sun"
docname = "the Sun"
mass = 1.989e30
radius = 6.9634e8
eccentricity = 0.0
periapsis = 2.36518e20
# I can't seem to find the orientation of the Sun's orbit
inclination = 0.0
arg_pe = 0.0
long_asc_node = 0.0
mean_anomaly = 0.0
color = 0xFFF3EAFF

################ MAIN PLANETS ################

[mercury]
name = "Mercury"
description = "the closest planet to the Sun"
mass = 3.3011e23
radius = 2.4397e6
eccentricity = 0.2056487136366576
periapsis = 46000004.62274023
inclination = 7.003449263392496
arg_pe = 29.19828371743479
long_asc_node = 48.298988699309
mean_anomaly = 127.5136171412925
color = 0xE8E7E5FF

[venus]
name = "Venus"
description = "the second planet from the Sun"
mass = 4.8675e24
radius = 6.0518e6
eccentricity = 0.00678658356338368
periapsis = 107474542.7159471
inclination = 3.394401885661878
arg_pe = 54.8117750466469
long_asc_node = 76.60729835593617
mean_anomaly = 352.4560334357049
color = 0xF4E6C9FF

[earth]
name = "Earth"
description = "the third planet from the Sun"
mass = 5.972e24
radius = 6.371e6
eccentricity = 0.01693834775580156
periapsis = 147116234.0253806
inclination = 0.003106965593817166
arg_pe = 284.7407071661571
long_asc_node = 177.0237556801468
mean_anomaly = 264.6136670969164
color = 0x9ADAEBFF

[mars]
name = "Mars"
description = "the fourth planet from the Sun"
mass = 6.4171e23
radius = 3.3895e6
eccentricity = 0.09349460601245496
periapsis = 206623101.1262357
inclination = 1.847524403097089
arg_pe = 286.6457500404398
long_asc_node = 49.48375620119834
mean_anomaly = 265.841922915472
color = 0xFAC192FF

[jupiter]
name = "Jupiter"
description = "the fifth planet from the Sun"
mass = 1.8982e27
radius = 6.9911e7
eccentricity = 0.04828933063430742
periapsis = 740769821.497716
inclination = 1.303471777729562
arg_pe = 273.6540261329467
long_asc_node = 100.5179245701896
mean_anomaly = 81.34815343515955
color = 0xE1D6BFFF

[saturn]
name = "Saturn"
description = "the sixth planet from the Sun"
mass = 5.6834e26
radius = 5.8232e7
eccentricity = 0.05541470658876883
periapsis = 1349036841.699487
inclination = 2.486361382149396
arg_pe = 338.1286787688496
long_asc_node = 113.5564375471404
mean_anomaly = 273.0478564798767
color = 0xDEBB79FF

[uranus]
name = "Uranus"
description = "the seventh planet from the Sun"
mass = 8.681e25
radius = 2.5362e7
eccentricity = 0.04652097935035968
periapsis = 2751432371.503581
inclination = 0.7738074224980911
arg_pe = 91.04697493998832
long_asc_node = 73.99536345699181
mean_anomaly = 258.5705317566712
color = 0xD2EBF3FF

[neptune]
name = "Neptune"
description = "the eighth planet from the Sun"
mass = 1.02409e26
radius = 2.4341e7
eccentricity = 0.01148143090256965
periapsis = 4456177100.000404
inclination = 1.774489608457549
arg_pe = 273.5312953873977
long_asc_node = 131.9439698097146
mean_anomaly = 315.8816006072404
color = 0x8FACB6FF

################ MOONS ################

[luna]
name = "Luna"
docname = "the Moon"
description = "the only natural satellite of Earth"
mass = 7.342e22
radius = 1.7371e6
eccentricity = 0.06403194372218053
periapsis = 356739.1224265639
inclination = 5.251786164560237
arg_pe = 66.36763202882524
long_asc_node = 347.8381830378123
mean_anomaly = 196.4764652218578
color = 0xA19F9DFF

[phobos]
name = "Phobos"
description = "the first moon of Mars"
mass = 1.06e16
radius = 11080.0
eccentricity = 0.01516548943882722
periapsis = 9236.141150848018
inclination = 27.77596217742595
arg_pe = 118.066820241968
long_asc_node = 82.52333201827675
mean_anomaly = 75.14361922168872
color = 0xCBAFA1FF

[deimos]
name = "Deimos"
description = "the second moon of Mars"
mass = 1.51e15
radius = 6270.0
eccentricity = 0.0002313318154817066
periapsis = 23452.7808348859
inclination = 24.19049744227209
arg_pe = 51.69138196985961
long_asc_node = 81.05708926716292
mean_anomaly = 102.2635631803519
color = 0xD1C7BBFF

[io]
name = "Io"
description = "the innermost Galilean moon of Jupiter"
mass = 8.931938e22
radius = 1.8216e6
eccentricity = 0.004370817965656309
periapsis = 420185.0977036619
inclination = 2.200037981675353
arg_pe = 324.9581763192999
long_asc_node = 338.433765657278
mean_anomaly = 68.39822167183954
color = 0xFCF785FF

[europa]
name = "Europa"
description = "the second innermost Galilean moon of Jupiter"
mass = 4.79984e22
radius = 1.5608e6
eccentricity = 0.009023819889118495
periapsis = 665273.8156191049
inclination = 2.173957085780015
arg_pe = 145.8450533304958
long_asc_node = 325.8724284600516
mean_anomaly = 221.7339377742665
color = 0xD9D2BFFF

[ganymede]
name = "Ganymede"
description = "the most massive and second outermost Galilean moon of Jupiter"
mass = 1.4819e23
radius = 2.6341e6
eccentricity = 0.002317642043459766
periapsis = 1067957.329599608
inclination = 2.3375802268531
arg_pe = 347.7690058983741
long_asc_node = 339.298549952625
mean_anomaly = 257.1335309851282
color = 0xC8BCADFF

[callisto]
name = "Callisto"
description = "the outermost Galilean moon of Jupiter"
mass = 1.075938e23
radius = 2.4103e6
eccentricity = 0.00716667402831101
periapsis = 1869478.25204344
inclination = 1.951118553067693
arg_pe = 32.11293393393926
long_asc_node = 336.7004531905803
mean_anomaly = 183.620779969283
color = 0x2A2720FF

[titan]
name = "Titan"
description = "the largest moon of Saturn"
mass = 1.34518e23
radius = 2.57473e6
eccentricity = 0.02882308191174093
periapsis = 1186729.250918975
inclination = 27.70978091760443
arg_pe = 177.811382130198
long_asc_node = 169.0759976091919
mean_anomaly = 0.1071660428063306
color = 0xF0DF87FF

[enceladus]
name = "Enceladus"
description = """\
one of the most reflective bodies \
in the Solar system and a moon of Saturn"""
mass = 1.080318e20
radius = 252100.0
eccentricity = 0.004603966908333064
periapsis = 237314.1998817407
inclination = 28.05545867725937
arg_pe = 87.93098346934126
long_asc_node = 169.5215891601628
mean_anomaly = 80.66247713532142
color = 0xFFFFFFFF

[mimas]
name = "Mimas"
description = "the moon of Saturn that looks similar to a Death Star"
mass = 3.75094e19
radius = 198200.0
eccentricity = 0.01834622161228059
periapsis = 182599.6456318654
inclination = 27.90504564713535
arg_pe = 159.2193150606826
long_asc_node = 172.8722899071802
mean_anomaly = 109.4619489229227
color = 0xe6e6e6FF

[tethys]
name = "Tethys"
description = "the fifth-largest moon of Saturn"
mass = 6.1749e20
radius = 531100.0
eccentricity = 0.0008509814288753383
periapsis = 294727.0548249478
inclination = 27.02789255753268

arg_pe = 135.4028297731129
long_asc_node = 170.3518350652559
mean_anomaly = 357.1977667349988
color = 0xFFFFFFFF                # literally > 1 geometric albedo bro how tf üò≠

[iapetus]
name = "Iapetus"
description = "the outermost of Saturn's large moons"
mass = 1.80565e21
radius = 734400.0
eccentricity = 0.02963197262058271
periapsis = 3458095.473493696
inclination = 17.0061991689635

arg_pe = 231.895712379834
long_asc_node = 138.9126282491323
mean_anomaly = 28.5557980003619
color = 0x999594FF

[titania]
name = "Titania"
description = "the largest moon of Uranus"
mass = 3.4550e21
radius = 788400.0
eccentricity = 0.001952606838943729
periapsis = 435446.2561268456
inclination = 97.76381895901389

arg_pe = 225.343641649572
long_asc_node = 167.6416906947348
mean_anomaly = 2.701402452193537
color = 0xD6C9B6FF

[oberon]
name = "Oberon"
description = "the second-largest moon of Uranus"
mass = 3.1104e21
radius = 761400.0
eccentricity = 0.0007586297352135548
periapsis = 583017.3145208834
inclination = 97.90548420462999

arg_pe = 209.5565921786809
long_asc_node = 167.7103350297154
mean_anomaly = 240.2690828228574
color = 0xA59E96FF

[triton]
name = "Triton"
description = "the largest moon of Neptune"
mass = 2.1389e22
radius = 1353400.0
eccentricity = 3.158226192842885e-05
periapsis = 354755.3421111452
inclination = 129.1490440271335

arg_pe = 306.1085494037479
long_asc_node = 222.5876064506128
mean_anomaly = 23.6480040227059
color = 0xA7A7A7FF

[proteus]
name = "Proteus"
docname = "Proteus (Neptune VIII)"
description = "The second-largest moon of Neptune"
mass = 2e19
radius = 210000.0
eccentricity = 0.0004790628083249919
periapsis = 117617.0916034098
inclination = 29.06320396831997

arg_pe = 23.67638431125431
long_asc_node = 48.71015549065658
mean_anomaly = 77.56363006232743
color = 0x2E2E2EFF

[nereid]
name = "Nereid"
docname = "Nereid (Neptune II)"
description = "the third-largest moon of Neptune"
mass = 3.57e19
radius = 178500.0
eccentricity = 0.7450218404457777
periapsis = 1406513.511689433
inclination = 4.991235136876663
arg_pe = 296.0565488126072
long_asc_node = 319.9975699264231
mean_anomaly = 254.7614392422707
color = 0x434343FF

[weywot]
name = "Weywot"
docname = "(50000) Quaoar I, a.k.a. Weywot"
description = "the moon of the dwarf planet Quaoar"
# Weywot's mass has not been measured.
# I extrapolated from the mean density of Quaoar:
# ~1.7 g/cm^3
# Weywot's radius is about 1e5 meters
# Therefore its volume is:
# V = 4/3 * pi * (1e5)^3 in cubic meters
# V = 4.18879e15 m^3
# Its mass is then:
# M = 1.7 g/cm^3 * 4.18879e15 m^3
# M = 1.7e3 kg/m^3 * 4.18879e15 m^3
# M = 7.12e18 kg
# (approximately)
mass = 7.12e18
radius = 1e5
eccentricity = 0.2526715693673015
periapsis = 10102.09277655204
# I only found inclination to the ecliptic.
# I couldn't find one in relation to Quaoar's equator.
inclination = 154.3222815054793
arg_pe = 36.30278860781244
long_asc_node = 330.9962127777341
# I couldn't find the mean anomaly
mean_anomaly = 345.0741929669152
# Weywot is very dark with an albedo of ‚âà0.04
color = [70, 70, 70]

[charon]
name = "Charon"
docname = "(134340) Pluto I, a.k.a. Charon"
description = "the largest moon orbiting Pluto"
mass = 1.5897e21
radius = 6.06e5
eccentricity = 0.0001608486966873896
periapsis = 19592.60950706746
inclination = 112.8878177315733
# Could not find number for arg. of pe.
arg_pe = 172.3257651710914
long_asc_node = 227.3929905537143
# Could not find number for mean anomaly
mean_anomaly = 102.4688418442574
color = 0x5E564BFF

[dysnomia]
name = "Dysnomia"
docname = "(136199) Eris I Dysnomia"
description = "the moon of the dwarf planet Eris"
mass = 8.2e19
radius = 3.075e5
eccentricity = 0.006136716777589243
periapsis = 37045.73194467473
inclination = 61.60967858787004
arg_pe = 155.2700923066068
long_asc_node = 139.0978068029031
# Could not find mean anomaly number
mean_anomaly = 310.2692544786455
color = [78, 75, 73]

################ MINOR PLANETS ################

[ceres]
name = "Ceres"
docname = "1 Ceres"
description = "a dwarf planet in the asteroid belt"
mass = 9.3839e20
radius = 469700.0
eccentricity = 0.07952993433729805
periapsis = 380842657.1089152
inclination = 10.58782054814408
arg_pe = 73.2858033590456
long_asc_node = 80.25048376518417
mean_anomaly = 219.9076580721496
color = 0x68585980

[vesta]
name = "Vesta"
docname = "4 Vesta"
description = "a large asteroid in the asteroid belt"
mass = 2.590271e20
radius = 262700.0
eccentricity = 0.09014966349360137
periapsis = 321429791.435468
inclination = 7.144050463866741
arg_pe = 151.5503649923697
long_asc_node = 103.7023121089329
mean_anomaly = 12.04283791785766
color = 0x85837780

[quaoar]
name = "Quaoar"
docname = "50000 Quaoar"
description = "a dwarf planet in the Kuiper belt"
mass = 1.2e21
radius = 5.45e5
eccentricity = 0.03605179841289581
periapsis = 6222224636.241554
inclination = 7.991326155728335
arg_pe = 164.0072962320328
long_asc_node = 188.9763942825857
mean_anomaly = 291.2209440318058
color = [99, 87, 82, 80]

[sedna]
name = "Sedna"
docname = "90377 Sedna"
description = "a dwarf planet, sednoid, and extreme trans-Neptunian object"
# Mass not yet directly measured
# Estimate used
mass = 2e21
radius = 5e5
eccentricity = 0.8615855169863725
periapsis = 11404440957.39675
inclination = 11.92614113993766
arg_pe = 310.9866352087582
long_asc_node = 144.4688089663313
mean_anomaly = 358.6090192162926
color = [159, 62, 45, 128]

[leleakuhonua]
name = "LeleƒÅk≈´honua"
docname = "541132 LeleƒÅk≈´honua"
description = "a sednoid and extreme trans-Neptunian object"
# Mass not yet directly measured
# Estimate used
mass = 1e19
radius = 1.1e5
eccentricity = 0.9540534065743915
periapsis = 9683254374.359396
inclination = 11.67881993502853
arg_pe = 118.1070157451529
long_asc_node = 301.1299462075255
mean_anomaly = 359.6404581469566
color = [128, 128, 128, 128]

[pluto]
name = "Pluto"
docname = "134340 Pluto"
description = "a famous dwarf planet in the Kuiper belt"
mass = 1.3025e22
radius = 1.1883e6
eccentricity = 0.2488495282904834
periapsis = 4465705101.419454
inclination = 17.12435507868083
arg_pe = 115.4078719281033
long_asc_node = 110.2967674129237
mean_anomaly = 50.89867343300205
color = 0xA0948680

[haumea]
name = "Haumea"
docname = "136108 Haumea"
description = "a dwarf planet in the Kuiper belt"
mass = 4e21
radius = 7.8e5
eccentricity = 0.1961564473406506
periapsis = 5169795042.924812
inclination = 28.20838347091716
arg_pe = 240.9299763298903
long_asc_node = 121.8031736050018
mean_anomaly = 222.1016706380275
color = [190, 189, 192, 80]

[eris]
name = "Eris"
docname = "136199 Eris"
description = "a dwarf planet, and a trans-Neptunian and scattered disc object"
mass = 1.6466e22
radius = 1.163e6
eccentricity = 0.4365858712404583
periapsis = 5732563520.52879
inclination = 43.85368507624997
arg_pe = 150.720679371836
long_asc_node = 36.0332276396297
mean_anomaly = 211.3475049588154
color = [239, 238, 242, 80]

[makemake]
name = "Makemake"
docname = "136472 Makemake"
description = "a dwarf planet in the Kuiper belt"
mass = 3.1e21
radius = 7.15e5
eccentricity = 0.1608740659483736
periapsis = 5710780915.476201
inclination = 29.03316426220861
arg_pe = 297.0548283469257
long_asc_node = 79.26383731409369
mean_anomaly = 169.1707854570842
color = [209, 190, 185, 80]

################ ARTIFICIAL SATELLITES ################
[parker_solar_probe]
name = "Parker Solar Probe"
description = "an artificial satellite very close to the Sun"
mass = 555.0
radius = 1.5
eccentricity = 0.8819369635896435
periapsis = 6861531.628837569
inclination = 3.395252013201449
arg_pe = 68.46120900218231
long_asc_node = 76.64426278679525
mean_anomaly = 48.1922227213533
color = 0xFFFF4444

[voyager_1]
name = "Voyager 1"
description = "an artificial satellite in the interstellar medium"
mass = 721.9
radius = 4.0
eccentricity = 3.69327025404461
periapsis = 1296200807.746376
inclination = 35.79487225780857
arg_pe = 337.9764867885052
long_asc_node = 179.1497243717326
mean_anomaly = 2855.166829484127
color = 0xFFFF4444

[voyager_2]
name = "Voyager 2"
description = "an artificial satellite in the interstellar medium"
mass = 721.9
radius = 4.0
eccentricity = 6.285358348080489
periapsis = 3180538467.429934
inclination = 79.00252628927736
arg_pe = 130.0457656032997
long_asc_node = 101.824552157977
mean_anomaly = 1893.051519975169
color = 0xFFFF4444

[new_horizons]
name = "New Horizons"
description = "an artificial satellite in escape trajectory from the Sun"
mass = 401.0
radius = 1.4
eccentricity = 1.408815052157123
periapsis = 345060492.7121326
inclination = 2.264656261599127
arg_pe = 291.3721100709962
long_asc_node = 226.6282877030447
mean_anomaly = 527.7210712507145
color = 0xFFFF4444

[pioneer_10]
name = "Pioneer 10"
description = "an inactive artificial satellite in escape trajectory from the Sun"
mass = 258.0
# unsure of real dimensions, used ballpark estimate
radius = 5.0
eccentricity = 1.749934503765944
periapsis = 777258886.4623048
inclination = 3.131175993640667
arg_pe = 346.6052653690019
long_asc_node = 332.6667947734815
mean_anomaly = 1023.748041894634
color = 0xFFFFFF44

[pioneer_11]
name = "Pioneer 11"
description = "an inactive artificial satellite in escape trajectory from the Sun"
mass = 258.5
# unsure of real dimensions, used ballpark estimate
radius = 5.0
eccentricity = 2.133725880354945
periapsis = 1380820478.475073
inclination = 16.64744588128611
arg_pe = 12.62549515042181
long_asc_node = 160.2361285469366
mean_anomaly = 710.2769308456657
color = 0xFFFFFF44

[geostationary_sat]
name = "Geostationary Satellite"
docname = "a geostationary satellite"
description = "located 42,164 km from the center of the parent body"
mass = 1000.0
radius = 10.0
eccentricity = 0.0
periapsis = 42164000.0
inclination = 0.0
arg_pe = 0.0
long_asc_node = 0.0
mean_anomaly = 0.0
color = 0xFFFFFF44
